---
logging.level.com.syscom: INFO
logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.pattern.file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
management.endpoints.web.base-path: /manage
server.port: 8080
spring.application.name: users-kafka-producer
spring.jackson.serialization.write-dates-as-timestamps: false
spring.datasource.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
spring.datasource.platform: postgres
spring.datasource.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.url: jdbc:p6spy:postgresql://localhost:5432/db_users_1
spring.datasource.username: db_users_1
spring.datasource.password: db_users_1
spring.jpa.database: POSTGRESQL
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.kafka.bootstrap-servers: localhost:9092
spring.kafka.producer.topic.user.upsert: users-upsert
spring.kafka.producer.topic.user.deleted: users-deleted
spring.kafka.producer.topic.category.upsert: category-upsert
spring.kafka.producer.topic.category.deleted: category-deleted
