logging:
  level:
    com:
      syscom: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
management:
  endpoints:
    web:
      base-path: /manage
server:
  port: 8080
spring:
  application:
    name: users-kafka-producer
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:postgresql://localhost:5432/db_users
    username: db_users
    password: db_users
    platform: postgres
  jpa:
    database: postgresql
    show-sql: false
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic:
        user:
          upsert: users-upsert
          deleted: users-deleted
        category:
          upsert: category-upsert
          deleted: category-deleted
